source 'https://rubygems.org'

### core dependencies
gem 'rails', '4.2.0'
gem 'pg'
gem 'bundler', '1.10.6'
# gem 'unicorn'

### front-end dependencies
gem 'animate-rails'
gem 'bootstrap-sass'
gem 'google-webfonts-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

### back-end dependencies
gem 'annotate'
gem 'devise'
gem 'kaminari', '~> 0.16'
gem 'paperclip', '~> 4.3'
gem 'pundit', '~> 1.0'

### documentation
gem 'sdoc', '~> 0.4.0', group: :doc

### production
group :production do
end

### development and test
group :development, :test do
  gem 'factory_girl_rails', '~> 4.4'
  gem 'faker', '~> 1.4.3'
  gem 'populator'
  gem 'rspec-rails', '~> 3.0'
  gem 'spring'
end

### development environment only
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'web-console', '~> 2.0'
end

### test environment only
group :test do
  gem 'capybara', '~> 2.4.4'
  gem 'shoulda'
end
