source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use postgresql as the database for Active Record
gem 'pg'
# Adding Bootstrap
gem 'bootstrap-sass'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Build a user authentication with Devise
gem 'devise'

# Use Pundit for user-resource authorization
gem 'pundit', '~> 1.0'

# Adding CSS animation
gem 'animate-rails'
# Google Fonts
gem 'google-webfonts-rails'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Paperclip to upload files
gem 'paperclip', '~> 4.3'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Kaminari for pagination
gem 'kaminari', '~> 0.16'

group :development, :test do
  # Install rspec for testing
  gem 'rspec-rails', '~> 3.0'

  # Install Capybara for testing
  gem 'capybara', '~> 2.4.4'

  # Install Shoulda Matchers for validation testing
  gem 'shoulda'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # Factory Girl
  gem 'factory_girl_rails'

  # Install Faker and Popullator to seed data to the DB
  gem 'faker', '~> 1.4.3'
  gem 'populator'

  # Use quiet assets in development
  gem 'quiet_assets'

end
